/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEmployeeGet$Json } from '../fn/employee/api-employee-get-json';
import { ApiEmployeeGet$Json$Params } from '../fn/employee/api-employee-get-json';
import { apiEmployeeGet$Plain } from '../fn/employee/api-employee-get-plain';
import { ApiEmployeeGet$Plain$Params } from '../fn/employee/api-employee-get-plain';
import { EmployeeDto } from '../models/employee-dto';

@Injectable({ providedIn: 'root' })
export class EmployeeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEmployeeGet()` */
  static readonly ApiEmployeeGetPath = '/api/Employee';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeeGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet$Plain$Response(params?: ApiEmployeeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return apiEmployeeGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeeGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet$Plain(params?: ApiEmployeeGet$Plain$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.apiEmployeeGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeeGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet$Json$Response(params?: ApiEmployeeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return apiEmployeeGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeeGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeeGet$Json(params?: ApiEmployeeGet$Json$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.apiEmployeeGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

}
