/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiShipperGet$Json } from '../fn/shipper/api-shipper-get-json';
import { ApiShipperGet$Json$Params } from '../fn/shipper/api-shipper-get-json';
import { apiShipperGet$Plain } from '../fn/shipper/api-shipper-get-plain';
import { ApiShipperGet$Plain$Params } from '../fn/shipper/api-shipper-get-plain';
import { ShipperDto } from '../models/shipper-dto';

@Injectable({ providedIn: 'root' })
export class ShipperService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiShipperGet()` */
  static readonly ApiShipperGetPath = '/api/Shipper';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShipperGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet$Plain$Response(params?: ApiShipperGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipperDto>>> {
    return apiShipperGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShipperGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet$Plain(params?: ApiShipperGet$Plain$Params, context?: HttpContext): Observable<Array<ShipperDto>> {
    return this.apiShipperGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ShipperDto>>): Array<ShipperDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShipperGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet$Json$Response(params?: ApiShipperGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipperDto>>> {
    return apiShipperGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShipperGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShipperGet$Json(params?: ApiShipperGet$Json$Params, context?: HttpContext): Observable<Array<ShipperDto>> {
    return this.apiShipperGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ShipperDto>>): Array<ShipperDto> => r.body)
    );
  }

}
