/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CustomerPredictionDto } from './models/customer-prediction-dto';
export type { EmployeeDto } from './models/employee-dto';
export type { OrderDetailDto } from './models/order-detail-dto';
export type { OrderDto } from './models/order-dto';
export type { ProductDto } from './models/product-dto';
export type { ShipperDto } from './models/shipper-dto';
