/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CustomerPredictionService } from './services/customer-prediction.service';
export { EmployeeService } from './services/employee.service';
export { OrderService } from './services/order.service';
export { ProductService } from './services/product.service';
export { ShipperService } from './services/shipper.service';
